# Distribución Normal

## Objetivos

Aplicar herramientas estadísticas para analizar si una variable se distribuye normalmente y calcular probabilidades, utilizando Python como apoyo.

*Nota: Este laboratorio está diseñado para desarrollar razonamiento estadístico. Evita el uso de herramientas de IA para responder las preguntas a menos que esto sea explícitamente sugerido* 🤖. *En su lugar, enfócate en aplicar los conceptos revisados.*

## Actividad 1

Una empresa de telecomunicaciones está evaluando los pagos mensuales realizados por sus clientes en los últimos 12 meses. Los datos provienen de distintas compañías y abarcan una muestra de más de 500 clientes. El equipo de analistas necesita saber si el pago mensual se comporta como una variable normalmente distribuida, ya que algunas decisiones estadísticas y operativas requieren este supuesto.

Descarga la **<a href="https://docs.google.com/spreadsheets/d/1eJ_4kf_vWJ9PVIzxiq7cN_B7qdZRFy21/export?format=xlsx
">base de datos aquí</a>** y responde las siguientes preguntas:

1. Calcula la media, la mediana y la moda de la variable Pago mensual. ¿Los valores obtenidos son similares entre sí? Analiza lo que esto indica sobre la simetría de la distribución de los datos.

In [5]:
import pandas as pd

df_1=pd.read_excel("/content/Base8_1.xlsx")

df_1.head()


,id Cliente,Pago mensual ($),Género,Compañía,Permanencia en la compañía (años),Gama
0,28866,23209,Femenino,ENTEL,2,Baja
1,18840,19454,Femenino,ENTEL,5,Media
2,52883,17353,Femenino,ENTEL,3,Media
3,86965,19341,Femenino,ENTEL,1,Baja
4,57092,20582,Masculino,WOM,1,Baja


In [10]:
media=df_1["Pago mensual ($)"].median()
moda=df_1["Pago mensual ($)"].mode()
mediana=df_1["Pago mensual ($)"].median()

print(f"Media: {media}, Mediana: {mediana}")

if len(moda)==1:
  print(f'Moda: ${moda.to_list()[0]}')
else:
  print(f"Moda: ${moda.to_list()}")

minimo=df_1["Pago mensual ($)"].min()
maximo=df_1["Pago mensual ($)"].max()

print(f"\n Minimo: ${minimo}\n Maximo: ${maximo}")

Media: 21324.0, Mediana: 21324.0
Moda: $22564

 Minimo: $10676
 Maximo: $32221


2. Calcula e interpreta el coeficiente de asimetría y el coeficiente de curtosis para la variable Pago mensual. ¿Estos valores son consistentes con los esperados en una distribución normal? Justifica tu respuesta.

In [15]:
from scipy.stats import skew, kurtosis

#Coeficiente de asimetria:
asimetria=skew(df_1["Pago mensual ($)"])

#Curtosis
curtosis=kurtosis(df_1["Pago mensual ($)"])

print(f"Coefiiciente de asimetria: {asimetria:.2f}")
print(f"Coeficiente de curtosis: {curtosis:.2f}")

Coefiiciente de asimetria: 0.03
Coeficiente de curtosis: 0.10


3. Observa el siguiente histograma correspondiente a la variable Pago mensual. ¿Los resultados obtenidos en los incisos anteriores son coherentes con forma del gráfico?  Describe brevemente su simetría y la forma de la distribución.

<center>

<img src = "https://i.ibb.co/VY8CgNZB/Captura-de-pantalla-2025-10-07-155703.png" width = "800"/>
</center>

4. Considerando que la variable Pago mensual sigue una distribución aproximadamente normal, responde las siguientes preguntas:

$\hspace{1cm}$ a)  ¿Cuál es la probabilidad de que un cliente pague menos de \$18.000 al mes?

$\hspace{1cm}$ b) ¿Cuál es la probabilidad de que un cliente pague más de \$25.000 al mes?

$\hspace{1cm}$ c) ¿Cuál es la probabilidad de que un cliente pague entre \$20.000 y \$24.000 al mes?

In [19]:
#Calcular probabilidades:
import scipy.stats as stats

media_1=df_1["Pago mensual ($)"].mean()
desviacion_estandar=df_1["Pago mensual ($)"].std()

# Use stats.norm.cdf
p_menor_18000 = stats.norm.cdf(18000, loc=media_1, scale=desviacion_estandar) * 100

p_mayor_25000 = (1 - stats.norm.cdf(25000, loc=media_1, scale=desviacion_estandar)) * 100

p_entre_20_24 = (stats.norm.cdf(24000, loc=media_1, scale=desviacion_estandar) - stats.norm.cdf(20000, loc=media_1, scale=desviacion_estandar)) * 100

print(f"Probabilidad de que un cliente pague menos de $18.000 al mes: {p_menor_18000:.2f}%")
print(f"Probabilidad de que un cliente pague más de $25.000 al mes: {p_mayor_25000:.2f}%")
print(f"Probabilidad de que un cliente pague entre $20.000 y $24.000 al mes: {p_entre_20_24:.2f}%")

Probabilidad de que un cliente pague menos de $18.000 al mes: 17.12%
Probabilidad de que un cliente pague más de $25.000 al mes: 14.47%
Probabilidad de que un cliente pague entre $20.000 y $24.000 al mes: 42.64%


5. La empresa desea lanzar un nuevo plan promocional dirigido a clientes cuyo pago mensual se encuentra entre \$20.000 y \$24.000. Con base en los resultados obtenidos, estima qué porcentaje de clientes pertenece a este rango. ¿Consideras adecuada esta segmentación desde el punto de vista del alcance? Justifica tu respuesta en función del comportamiento de la distribución de los datos.



## Actividad 2

Una consultora de datos está analizando los ingresos mensuales (en miles de pesos) de trabajadores independientes del sector tecnológico, con el objetivo de describir el comportamiento de esta variable y evaluar las características de su distribución. Esta información permitirá identificar patrones en los ingresos del sector y apoyar la toma de decisiones basada en datos.

Puedes descargar la **<a href="https://docs.google.com/spreadsheets/d/1swwzoHtZu_e_MELga14aekX4iax8Wawq/export?format=xlsx
">base de datos aquí</a>**, para responder las siguientes preguntas:

1. Calcula la media, mediana y moda del ingreso mensual. Considerando el rango de la distribución, ¿los valores están cercanos entre sí? ¿La moda es única?

2. Calcula e interpreta el coeficiente de asimetría y el coeficiente de curtosis de la variable.
¿Qué sugieren estos valores sobre la forma y concentración de los datos?

3. Observa el siguiente histograma correspondiente a la variable Ingreso mensual. ¿Los resultados obtenidos en los incisos anteriores son coherentes con la forma del gráfico? Describe brevemente su simetría y la forma de la distribución.

<center>

<img src = "https://i.ibb.co/jPV93rxG/Captura-de-pantalla-2025-10-17-123234.png" width = "800"/>
</center>

4. Considerando los análisis realizados en los incisos anteriores, ¿piensas que sería adecuado utilizar herramientas basadas en la distribución normal para tomar decisiones estadísticas? Justifica tu respuesta.

## Actividad 3

Una empresa de servicios tecnológicos ofrece soporte técnico remoto a sus clientes. El área de operaciones desea analizar los tiempos promedio de atención remota por trabajador, medidos en segundos, para tomar decisiones estratégicas.

La empresa ha determinado que esta variable se distribuye normalmente, con una media de 600,5 segundos y una desviación estándar de 78,4 segundos, en base a los registros de los últimos seis meses.

Importa la **<a href="https://drive.google.com/uc?export=download&id=10evq5_VmY1Mim6NCl9hugGGzjm5pTE-A
">base de datos</a>** y responde las siguientes preguntas:

1. La empresa está evaluando entregar un bono de eficiencia a los trabajadores cuyo tiempo de atención sea menor a 500 segundos. ¿Cuál es la probabilidad de que un trabajador seleccionado al azar cumpla con ese criterio?

2. Con base en la probabilidad obtenida anteriormente, determine el número estimado de trabajadores beneficiados e interprete este valor en relación con la implementación del bono de eficiencia.

3. ¿Piensas que es un umbral razonable para otorgar el bono? Justifica.

4. Se considera implementar una capacitación obligatoria dirigida a los trabajadores con tiempos de atención superiores a 660 segundos. Según este criterio, ¿cuál es la probabilidad de que un trabajador deba participar en dicha capacitación?

5. ¿La capacitación obligatoria afecta a un grupo reducido o amplio de trabajadores? Fundamenta tu respuesta con base en la probabilidad calculada y la distribución de los tiempos de atención.

6. La empresa desea optimizar sus procesos enfocándose en el grupo más representativo de trabajadores, es decir, aquellos que presentan tiempos de atención cercanos a lo habitual. ¿Cuál es la probabilidad de que un trabajador registre un tiempo de atención entre 520 y 680 segundos?

## Actividad 4

Una tienda en línea que vende una amplia variedad de productos analiza el tiempo de entrega (en días), el costo de transporte (en miles de pesos) y el peso (en kilogramos) de sus pedidos para mejorar su eficiencia operativa y la satisfacción del cliente. La tienda está interesada en estudiar la distribución del tiempo de entrega para poder predecir mejor los plazos de entrega y optimizar sus procesos logísticos. Las variables costo de transporte y peso siguen una distribución normal.

Importa la **<a href="https://drive.google.com/uc?export=download&id=1x83rV02Af-8UrWEYX1tkQ_Y9w_bS7f_k
">base de datos</a>** y responde las siguientes preguntas:

1. El Gerente de Logística necesita de tu asesoría para corroborar que la variable Costo de Transporte sigue una distribución normal. ¿Qué análisis realizarías para asesorar al gerente?

2. El gerente sostiene que la probabilidad de que un pedido tenga un peso mayor a 5 kilogramos supera el 10%. ¿Está en lo correcto? Justifica tu respuesta.

3. En un mes con 10.000 entregas, el gerente te solicita calcular el número esperado de pedidos con un peso superior a 5 kilogramos. ¿Cuál sería tu respuesta?

4. El área de planificación sostiene que la probabilidad de que un pedido pese menos de 3 kilogramos es baja, es decir, entre un 5% y un 20%, ya que la mayoría de los productos son medianos o grandes. ¿Es correcta esta afirmación? Justifique su respuesta con base en el análisis de los datos.

5. Si la probabilidad de que una entrega tenga un costo de transporte superior a 280 mil pesos es menor al 30%, el gerente entregará un bono de 100 mil pesos a los trabajadores. ¿Corresponde entregar el bono? Justifique su respuesta.

6. El gerente desea identificar el rango de pedidos que representan el “comportamiento típico” en términos de costo de transporte. Se estima que este rango se encuentra entre 240 mil y 280 mil pesos. ¿Cuál es la probabilidad de que una entrega se ubique dentro de este intervalo? ¿Consideras que este rango refleja efectivamente el comportamiento más común?

7. En el análisis se utilizaron herramientas estadísticas para evaluar las afirmaciones realizadas por el equipo de logística. ¿Qué importancia tiene contar con evidencia basada en datos para la toma de decisiones en una operación real? ¿Qué riesgos podrían presentarse si las decisiones se fundamentaran únicamente en la intuición o la experiencia?